import type { Metadata } from "next";
import { IBM_Plex_Sans as Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./providers/SessionProvider";
import Header from "./components/Header.";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en" className="bg-gray-700 py-6">
        <body className={inter.className}>
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </SessionWrapper>
  );
}
